DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_digest TEXT NOT NULL,
  firstname VARCHAR(255) UNIQUE NOT NULL,
  lastname VARCHAR(255) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS stocks;
CREATE TABLE IF NOT EXISTS stocks (
  id SERIAL PRIMARY KEY,
  symbol VARCHAR(255) UNIQUE NOT NULL,
  companyName VARCHAR(255) UNIQUE NOT NULL,
  primaryExchange VARCHAR(255) NOT NULL,
  sector VARCHAR(255) NOT NULL,
  open INTEGER,
  openTime INTEGER,
  close INTEGER,
  closeTime INTEGER,
  latestPrice INTEGER
)
